/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Region = {
  _id: string;
  _type: "region";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  province?: string;
  img?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  text?: Array<string>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Stage = {
  _id: string;
  _type: "stage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  origin?: string;
  destiny?: string;
  wayPoints?: Array<string>;
  slug?: Slug;
  description?: string;
  mapUrl?: string;
  videoUrl?: string;
  imgs?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  trailLocations?: Array<string>;
  allocations?: Array<string>;
  technicalDetails?: {
    distance?: number;
    duration?: number;
    initialHeight?: number;
    finalHeight?: number;
    minHeight?: number;
    maxHeight?: number;
    cumulativeAscent?: number;
    cumulativeDescent?: number;
  };
  notes?: Array<string>;
};

export type Subscriber = {
  _id: string;
  _type: "subscriber";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  displayName?: string;
  email?: string;
  clerkId?: string;
  stripeCustomerId?: string;
  currentSubscription?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscription";
  };
  createdStripeAt?: string;
  createdSubscriberAt?: string;
};

export type Subscription = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subscriber?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscriber";
  };
  stripeSubscriptionId?: string;
  stripeCustomerId?: string;
  stripePriceId?: string;
  stripeProductId?: string;
  productName?: string;
  unit_amount?: number;
  priceInterval?: "month" | "year";
  status?: "active" | "past_due" | "canceled" | "incomplete";
  current_period_end?: string;
  canceled_at?: string;
  createdAt?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Region | SanityImageCrop | SanityImageHotspot | Slug | Stage | Subscriber | Subscription | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/pelegrinatges/region/getRegionBySlug.ts
// Variable: getRegionBySlugQuery
// Query: *[_type == 'region' && slug.current == $slug][0]{    name,    "slug": slug.current,    province,    img{      asset->{        url      },      alt    },    text  }
export type GetRegionBySlugQueryResult = {
  name: string | null;
  slug: string | null;
  province: string | null;
  img: {
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  text: Array<string> | null;
} | null;

// Source: ./sanity/lib/pelegrinatges/region/getRegionsBySlugs.ts
// Variable: getRegionsBySlugsQuery
// Query: *[_type == 'region' && slug.current in $slugs][]
export type GetRegionsBySlugsQueryResult = Array<{
  _id: string;
  _type: "region";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  province?: string;
  img?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  text?: Array<string>;
}>;

// Source: ./sanity/lib/subscriber/createSubscriberIfNotExist.ts
// Variable: existingSubscriberQuery
// Query: *[_type == 'subscriber' && clerkId == $clerkId][0]
export type ExistingSubscriberQueryResult = {
  _id: string;
  _type: "subscriber";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  displayName?: string;
  email?: string;
  clerkId?: string;
  stripeCustomerId?: string;
  currentSubscription?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscription";
  };
  createdStripeAt?: string;
  createdSubscriberAt?: string;
} | null;

// Source: ./sanity/lib/subscriber/getIsEnrolled.ts
// Variable: getIsEnrolledQuery
// Query: *[_type == 'subscription' && subscriber._ref == $subscriberId && status == 'active'][0]
export type GetIsEnrolledQueryResult = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subscriber?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscriber";
  };
  stripeSubscriptionId?: string;
  stripeCustomerId?: string;
  stripePriceId?: string;
  stripeProductId?: string;
  productName?: string;
  unit_amount?: number;
  priceInterval?: "month" | "year";
  status?: "active" | "canceled" | "incomplete" | "past_due";
  current_period_end?: string;
  canceled_at?: string;
  createdAt?: string;
} | null;

// Source: ./sanity/lib/subscriber/getSubscriberByClerkId.ts
// Variable: getSubscriberByClerkIdQuery
// Query: *[_type == 'subscriber' && clerkId == $clerkId][0]
export type GetSubscriberByClerkIdQueryResult = {
  _id: string;
  _type: "subscriber";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  displayName?: string;
  email?: string;
  clerkId?: string;
  stripeCustomerId?: string;
  currentSubscription?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscription";
  };
  createdStripeAt?: string;
  createdSubscriberAt?: string;
} | null;

// Source: ./sanity/lib/subscription/cancelSubscription.ts
// Variable: getCurrentSubscriptionQuery
// Query: *[_type == 'subscription' && stripeSubscriptionId == $subscriptionId][0]
export type GetCurrentSubscriptionQueryResult = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subscriber?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscriber";
  };
  stripeSubscriptionId?: string;
  stripeCustomerId?: string;
  stripePriceId?: string;
  stripeProductId?: string;
  productName?: string;
  unit_amount?: number;
  priceInterval?: "month" | "year";
  status?: "active" | "canceled" | "incomplete" | "past_due";
  current_period_end?: string;
  canceled_at?: string;
  createdAt?: string;
} | null;

// Source: ./sanity/lib/subscription/createSubscription.ts
// Variable: subscriberActiveSubscriptionQuery
// Query: *[_type == 'subscription' && subscriber._ref == $subscriberId && status == 'active'][0]
export type SubscriberActiveSubscriptionQueryResult = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subscriber?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscriber";
  };
  stripeSubscriptionId?: string;
  stripeCustomerId?: string;
  stripePriceId?: string;
  stripeProductId?: string;
  productName?: string;
  unit_amount?: number;
  priceInterval?: "month" | "year";
  status?: "active" | "canceled" | "incomplete" | "past_due";
  current_period_end?: string;
  canceled_at?: string;
  createdAt?: string;
} | null;

// Source: ./sanity/lib/subscription/getActiveSubscriptionByClerkId.ts
// Variable: getSubscriptionQuery
// Query: *[_type == 'subscription' && subscriber->clerkId == $clerkId && status == 'active'][0]
export type GetSubscriptionQueryResult = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subscriber?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscriber";
  };
  stripeSubscriptionId?: string;
  stripeCustomerId?: string;
  stripePriceId?: string;
  stripeProductId?: string;
  productName?: string;
  unit_amount?: number;
  priceInterval?: "month" | "year";
  status?: "active" | "canceled" | "incomplete" | "past_due";
  current_period_end?: string;
  canceled_at?: string;
  createdAt?: string;
} | null;

// Source: ./sanity/lib/subscription/patchSubscription.ts
// Variable: getCurrentSubscriptionByStripeSubscriptionIdQuery
// Query: *[_type == 'subscription' && stripeSubscriptionId == $stripeSubscriptionId][0]
export type GetCurrentSubscriptionByStripeSubscriptionIdQueryResult = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subscriber?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscriber";
  };
  stripeSubscriptionId?: string;
  stripeCustomerId?: string;
  stripePriceId?: string;
  stripeProductId?: string;
  productName?: string;
  unit_amount?: number;
  priceInterval?: "month" | "year";
  status?: "active" | "canceled" | "incomplete" | "past_due";
  current_period_end?: string;
  canceled_at?: string;
  createdAt?: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == 'region' && slug.current == $slug][0]{\n    name,\n    \"slug\": slug.current,\n    province,\n    img{\n      asset->{\n        url\n      },\n      alt\n    },\n    text\n  }\n": GetRegionBySlugQueryResult;
    "*[_type == 'region' && slug.current in $slugs][]": GetRegionsBySlugsQueryResult;
    "*[_type == 'subscriber' && clerkId == $clerkId][0]": ExistingSubscriberQueryResult | GetSubscriberByClerkIdQueryResult;
    "*[_type == 'subscription' && subscriber._ref == $subscriberId && status == 'active'][0]": GetIsEnrolledQueryResult | SubscriberActiveSubscriptionQueryResult;
    "*[_type == 'subscription' && stripeSubscriptionId == $subscriptionId][0]": GetCurrentSubscriptionQueryResult;
    "*[_type == 'subscription' && subscriber->clerkId == $clerkId && status == 'active'][0]": GetSubscriptionQueryResult;
    "*[_type == 'subscription' && stripeSubscriptionId == $stripeSubscriptionId][0]": GetCurrentSubscriptionByStripeSubscriptionIdQueryResult;
  }
}
