/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type StageInternalTag = {
  _id: string;
  _type: "stageInternalTag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tag?: string;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type CurrentRoute = {
  _id: string;
  _type: "currentRoute";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  currentRoute?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "route";
  };
};

export type Poi = {
  _id: string;
  _type: "poi";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  location?: string;
  img?: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  text?: Array<string>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Region = {
  _id: string;
  _type: "region";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  province?: string;
  img?: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  text?: Array<string>;
};

export type Stage = {
  _id: string;
  _type: "stage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalTags?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "stageInternalTag";
  }>;
  origin?: string;
  destiny?: string;
  wayPoints?: Array<string>;
  slug?: Slug;
  description?: string;
  mapUrl?: string;
  videoUrl?: string;
  imgs?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  trailLocations?: Array<string>;
  regions?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "region";
  }>;
  pois?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "poi";
  }>;
  allocations?: Array<string>;
  technicalDetails?: {
    distance?: number;
    duration?: number;
    initialHeight?: number;
    finalHeight?: number;
    minHeight?: number;
    maxHeight?: number;
    cumulativeAscent?: number;
    cumulativeDescent?: number;
  };
  notes?: Array<string>;
};

export type Route = {
  _id: string;
  _type: "route";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalCode?: string;
  origin?: string;
  destiny?: string;
  wayPoints?: Array<string>;
  slug?: Slug;
  description?: Array<string>;
  mapUrl?: string;
  stages?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "stage";
  }>;
  notes?: Array<string>;
};

export type Subscriber = {
  _id: string;
  _type: "subscriber";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  displayName?: string;
  email?: string;
  clerkId?: string;
  stripeCustomerId?: string;
  currentSubscription?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscription";
  };
  createdStripeAt?: string;
  createdSubscriberAt?: string;
};

export type Subscription = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subscriber?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscriber";
  };
  stripeSubscriptionId?: string;
  stripeCustomerId?: string;
  stripePriceId?: string;
  stripeProductId?: string;
  productName?: string;
  unit_amount?: number;
  priceInterval?: "month" | "year";
  status?: "active" | "past_due" | "canceled" | "incomplete";
  current_period_end?: string;
  canceled_at?: string;
  createdAt?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = StageInternalTag | Slug | CurrentRoute | Poi | SanityImageCrop | SanityImageHotspot | Region | Stage | Route | Subscriber | Subscription | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/rutes-itineraris/currentRoute/getCurrentRoute.ts
// Variable: getCurrentRouteQuery
// Query: *[_type == 'currentRoute'][0]{      currentRoute->{        ...,        "slug": slug.current,        stages[]->{          "slug": slug.current        }      }    }.currentRoute
export type GetCurrentRouteQueryResult = {
  _id: string;
  _type: "route";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalCode?: string;
  origin?: string;
  destiny?: string;
  wayPoints?: Array<string>;
  slug: string | null;
  description?: Array<string>;
  mapUrl?: string;
  stages: Array<{
    slug: string | null;
  }> | null;
  notes?: Array<string>;
} | null;

// Source: ./sanity/lib/rutes-itineraris/poi/getPoiBySlug.ts
// Variable: getPoiBySlugQuery
// Query: *[_type == 'poi' && slug.current == $slug][0]{        ...,        "slug": slug.current,        img{          asset->{            url          },          alt        }      }
export type GetPoiBySlugQueryResult = {
  _id: string;
  _type: "poi";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug: string | null;
  location?: string;
  img: {
    asset: {
      url: string | null;
    };
    alt: string | null;
  } | null;
  text?: Array<string>;
} | null;

// Source: ./sanity/lib/rutes-itineraris/region/getRegionBySlug.ts
// Variable: getRegionBySlugQuery
// Query: *[_type == 'region' && slug.current == $slug][0]{    name,    "slug": slug.current,    province,    img{      asset->{        url      },      alt    },    text  }
export type GetRegionBySlugQueryResult = {
  name: string | null;
  slug: string | null;
  province: string | null;
  img: {
    asset: {
      url: string | null;
    };
    alt: string | null;
  } | null;
  text: Array<string> | null;
} | null;

// Source: ./sanity/lib/rutes-itineraris/region/getRegionsBySlugs.ts
// Variable: getRegionsBySlugsQuery
// Query: *[_type == 'region' && slug.current in $slugs][]{      name,      "slug": slug.current,      province,      img{        asset->{          url        },        alt      },      text    }
export type GetRegionsBySlugsQueryResult = Array<{
  name: string | null;
  slug: string | null;
  province: string | null;
  img: {
    asset: {
      url: string | null;
    };
    alt: string | null;
  } | null;
  text: Array<string> | null;
}>;

// Source: ./sanity/lib/rutes-itineraris/route/getAllRoutes.ts
// Variable: getAllRoutesQuery
// Query: *[_type == 'route'][]{        ...,        "slug": slug.current,        stages[]->{          "slug": slug.current        }      }
export type GetAllRoutesQueryResult = Array<{
  _id: string;
  _type: "route";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalCode?: string;
  origin?: string;
  destiny?: string;
  wayPoints?: Array<string>;
  slug: string | null;
  description?: Array<string>;
  mapUrl?: string;
  stages: Array<{
    slug: string | null;
  }> | null;
  notes?: Array<string>;
}>;

// Source: ./sanity/lib/rutes-itineraris/route/getRouteBySlug.ts
// Variable: getRouteBySlugQuery
// Query: *[_type == 'route' && slug.current == $slug][0]{        ...,        "slug": slug.current,        stages[]->{          "slug": slug.current        }      }
export type GetRouteBySlugQueryResult = {
  _id: string;
  _type: "route";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalCode?: string;
  origin?: string;
  destiny?: string;
  wayPoints?: Array<string>;
  slug: string | null;
  description?: Array<string>;
  mapUrl?: string;
  stages: Array<{
    slug: string | null;
  }> | null;
  notes?: Array<string>;
} | null;

// Source: ./sanity/lib/rutes-itineraris/stage/getStageBySlug.ts
// Variable: getStageBySlugQuery
// Query: *[_type == 'stage' && slug.current == $slug][0]{        ...,        "slug": slug.current,        regions[]->{          "slug": slug.current,          name,          img{            asset->{              url            },            alt          }        },        pois[]->{          "slug": slug.current,          name,          img{            asset->{              url            },            alt          }        },        imgs[]{          asset->{            url          },          alt        }      }
export type GetStageBySlugQueryResult = {
  _id: string;
  _type: "stage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalTags?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "stageInternalTag";
  }>;
  origin?: string;
  destiny?: string;
  wayPoints?: Array<string>;
  slug: string | null;
  description?: string;
  mapUrl?: string;
  videoUrl?: string;
  imgs: Array<{
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  }> | null;
  trailLocations?: Array<string>;
  regions: Array<{
    slug: string | null;
    name: string | null;
    img: {
      asset: {
        url: string | null;
      };
      alt: string | null;
    } | null;
  }> | null;
  pois: Array<{
    slug: string | null;
    name: string | null;
    img: {
      asset: {
        url: string | null;
      };
      alt: string | null;
    } | null;
  }> | null;
  allocations?: Array<string>;
  technicalDetails?: {
    distance?: number;
    duration?: number;
    initialHeight?: number;
    finalHeight?: number;
    minHeight?: number;
    maxHeight?: number;
    cumulativeAscent?: number;
    cumulativeDescent?: number;
  };
  notes?: Array<string>;
} | null;

// Source: ./sanity/lib/rutes-itineraris/stage/getStagesBySlugs.ts
// Variable: getStagesBySlugsQuery
// Query: *[_type == 'stage' && slug.current in $slugs][]{        ...,        "slug": slug.current,        regions[]->{          "slug": slug.current,          name,          img{            asset->{              url            },            alt          }        },        pois[]->{          "slug": slug.current,          name,          img{            asset->{              url            },            alt          }        },        imgs[]{          asset->{            url          },          alt        }      }
export type GetStagesBySlugsQueryResult = Array<{
  _id: string;
  _type: "stage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalTags?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "stageInternalTag";
  }>;
  origin?: string;
  destiny?: string;
  wayPoints?: Array<string>;
  slug: string | null;
  description?: string;
  mapUrl?: string;
  videoUrl?: string;
  imgs: Array<{
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  }> | null;
  trailLocations?: Array<string>;
  regions: Array<{
    slug: string | null;
    name: string | null;
    img: {
      asset: {
        url: string | null;
      };
      alt: string | null;
    } | null;
  }> | null;
  pois: Array<{
    slug: string | null;
    name: string | null;
    img: {
      asset: {
        url: string | null;
      };
      alt: string | null;
    } | null;
  }> | null;
  allocations?: Array<string>;
  technicalDetails?: {
    distance?: number;
    duration?: number;
    initialHeight?: number;
    finalHeight?: number;
    minHeight?: number;
    maxHeight?: number;
    cumulativeAscent?: number;
    cumulativeDescent?: number;
  };
  notes?: Array<string>;
}>;

// Source: ./sanity/lib/subscriber/createSubscriberIfNotExist.ts
// Variable: existingSubscriberQuery
// Query: *[_type == 'subscriber' && clerkId == $clerkId][0]
export type ExistingSubscriberQueryResult = {
  _id: string;
  _type: "subscriber";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  displayName?: string;
  email?: string;
  clerkId?: string;
  stripeCustomerId?: string;
  currentSubscription?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscription";
  };
  createdStripeAt?: string;
  createdSubscriberAt?: string;
} | null;

// Source: ./sanity/lib/subscriber/getIsEnrolled.ts
// Variable: getIsEnrolledQuery
// Query: *[_type == 'subscription' && subscriber._ref == $subscriberId && status == 'active'][0]
export type GetIsEnrolledQueryResult = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subscriber?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscriber";
  };
  stripeSubscriptionId?: string;
  stripeCustomerId?: string;
  stripePriceId?: string;
  stripeProductId?: string;
  productName?: string;
  unit_amount?: number;
  priceInterval?: "month" | "year";
  status?: "active" | "canceled" | "incomplete" | "past_due";
  current_period_end?: string;
  canceled_at?: string;
  createdAt?: string;
} | null;

// Source: ./sanity/lib/subscriber/getSubscriberByClerkId.ts
// Variable: getSubscriberByClerkIdQuery
// Query: *[_type == 'subscriber' && clerkId == $clerkId][0]
export type GetSubscriberByClerkIdQueryResult = {
  _id: string;
  _type: "subscriber";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  displayName?: string;
  email?: string;
  clerkId?: string;
  stripeCustomerId?: string;
  currentSubscription?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscription";
  };
  createdStripeAt?: string;
  createdSubscriberAt?: string;
} | null;

// Source: ./sanity/lib/subscription/cancelSubscription.ts
// Variable: getCurrentSubscriptionQuery
// Query: *[_type == 'subscription' && stripeSubscriptionId == $subscriptionId][0]
export type GetCurrentSubscriptionQueryResult = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subscriber?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscriber";
  };
  stripeSubscriptionId?: string;
  stripeCustomerId?: string;
  stripePriceId?: string;
  stripeProductId?: string;
  productName?: string;
  unit_amount?: number;
  priceInterval?: "month" | "year";
  status?: "active" | "canceled" | "incomplete" | "past_due";
  current_period_end?: string;
  canceled_at?: string;
  createdAt?: string;
} | null;

// Source: ./sanity/lib/subscription/createSubscription.ts
// Variable: subscriberActiveSubscriptionQuery
// Query: *[_type == 'subscription' && subscriber._ref == $subscriberId && status == 'active'][0]
export type SubscriberActiveSubscriptionQueryResult = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subscriber?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscriber";
  };
  stripeSubscriptionId?: string;
  stripeCustomerId?: string;
  stripePriceId?: string;
  stripeProductId?: string;
  productName?: string;
  unit_amount?: number;
  priceInterval?: "month" | "year";
  status?: "active" | "canceled" | "incomplete" | "past_due";
  current_period_end?: string;
  canceled_at?: string;
  createdAt?: string;
} | null;

// Source: ./sanity/lib/subscription/getActiveSubscriptionByClerkId.ts
// Variable: getSubscriptionQuery
// Query: *[_type == 'subscription' && subscriber->clerkId == $clerkId && status == 'active'][0]
export type GetSubscriptionQueryResult = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subscriber?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscriber";
  };
  stripeSubscriptionId?: string;
  stripeCustomerId?: string;
  stripePriceId?: string;
  stripeProductId?: string;
  productName?: string;
  unit_amount?: number;
  priceInterval?: "month" | "year";
  status?: "active" | "canceled" | "incomplete" | "past_due";
  current_period_end?: string;
  canceled_at?: string;
  createdAt?: string;
} | null;

// Source: ./sanity/lib/subscription/patchSubscription.ts
// Variable: getCurrentSubscriptionByStripeSubscriptionIdQuery
// Query: *[_type == 'subscription' && stripeSubscriptionId == $stripeSubscriptionId][0]
export type GetCurrentSubscriptionByStripeSubscriptionIdQueryResult = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subscriber?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "subscriber";
  };
  stripeSubscriptionId?: string;
  stripeCustomerId?: string;
  stripePriceId?: string;
  stripeProductId?: string;
  productName?: string;
  unit_amount?: number;
  priceInterval?: "month" | "year";
  status?: "active" | "canceled" | "incomplete" | "past_due";
  current_period_end?: string;
  canceled_at?: string;
  createdAt?: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n    *[_type == 'currentRoute'][0]{\n      currentRoute->{\n        ...,\n        \"slug\": slug.current,\n        stages[]->{\n          \"slug\": slug.current\n        }\n      }\n    }.currentRoute\n  ": GetCurrentRouteQueryResult;
    "\n      *[_type == 'poi' && slug.current == $slug][0]{\n        ...,\n        \"slug\": slug.current,\n        img{\n          asset->{\n            url\n          },\n          alt\n        }\n      }\n    ": GetPoiBySlugQueryResult;
    "\n  *[_type == 'region' && slug.current == $slug][0]{\n    name,\n    \"slug\": slug.current,\n    province,\n    img{\n      asset->{\n        url\n      },\n      alt\n    },\n    text\n  }\n": GetRegionBySlugQueryResult;
    "\n    *[_type == 'region' && slug.current in $slugs][]{\n      name,\n      \"slug\": slug.current,\n      province,\n      img{\n        asset->{\n          url\n        },\n        alt\n      },\n      text\n    }\n    ": GetRegionsBySlugsQueryResult;
    "\n      *[_type == 'route'][]{\n        ...,\n        \"slug\": slug.current,\n        stages[]->{\n          \"slug\": slug.current\n        }\n      }\n    ": GetAllRoutesQueryResult;
    "\n      *[_type == 'route' && slug.current == $slug][0]{\n        ...,\n        \"slug\": slug.current,\n        stages[]->{\n          \"slug\": slug.current\n        }\n      }\n    ": GetRouteBySlugQueryResult;
    "\n      *[_type == 'stage' && slug.current == $slug][0]{\n        ...,\n        \"slug\": slug.current,\n        regions[]->{\n          \"slug\": slug.current,\n          name,\n          img{\n            asset->{\n              url\n            },\n            alt\n          }\n        },\n        pois[]->{\n          \"slug\": slug.current,\n          name,\n          img{\n            asset->{\n              url\n            },\n            alt\n          }\n        },\n        imgs[]{\n          asset->{\n            url\n          },\n          alt\n        }\n      }\n    ": GetStageBySlugQueryResult;
    "\n      *[_type == 'stage' && slug.current in $slugs][]{\n        ...,\n        \"slug\": slug.current,\n        regions[]->{\n          \"slug\": slug.current,\n          name,\n          img{\n            asset->{\n              url\n            },\n            alt\n          }\n        },\n        pois[]->{\n          \"slug\": slug.current,\n          name,\n          img{\n            asset->{\n              url\n            },\n            alt\n          }\n        },\n        imgs[]{\n          asset->{\n            url\n          },\n          alt\n        }\n      }\n    ": GetStagesBySlugsQueryResult;
    "*[_type == 'subscriber' && clerkId == $clerkId][0]": ExistingSubscriberQueryResult | GetSubscriberByClerkIdQueryResult;
    "*[_type == 'subscription' && subscriber._ref == $subscriberId && status == 'active'][0]": GetIsEnrolledQueryResult | SubscriberActiveSubscriptionQueryResult;
    "*[_type == 'subscription' && stripeSubscriptionId == $subscriptionId][0]": GetCurrentSubscriptionQueryResult;
    "*[_type == 'subscription' && subscriber->clerkId == $clerkId && status == 'active'][0]": GetSubscriptionQueryResult;
    "*[_type == 'subscription' && stripeSubscriptionId == $stripeSubscriptionId][0]": GetCurrentSubscriptionByStripeSubscriptionIdQueryResult;
  }
}
